[package]
name = "rapier-godot"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", rev = "d3fe5c7" }
rapier3d = { version = "*", features = ["simd-stable"] }
thiserror = "1.0.44"
